### ISSUE TITLE
BLE service discovery fails (using any app), iPhone 6 / iOS 10.2.1

### ISSUE THREAD

**Issue by tschiemer** [NordicSemiconductor/ANT-Shared-Channel-Demo#1]
(As originally posted in the [Nordic Dev Zone](https://devzone.nordicsemi.com/question/113951/iosiphone-ble-service-discovery-timeout-with-ant-shared-channel-demo/))

Hi! 

Using the out of the box [ANT shared channel demo](http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v12.2.0%2Fant_examples_asc.html&cp=4_0_1_4_1_1) with a NRF52-DK board and the [iOS demo app](https://github.com/NordicSemiconductor/ANT-Shared-Channel-Demo) everything compiles and installs nicely, using the Android-based app [nRF Connect for Mobile](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) I can successfully connect and control the hub/peripherals, but the iOS App will not work.

The iOS app will successfully make a connection and start the service discovery with the given service identifier, but this service discovery always times out after +- 30 seconds thus disconnecting the two devices again.
Note: 30 seconds is the supervisor timeout in the hub-code, but changing the timeout or deactivating it has no effect.
Removing the service filter searching for any services within the iOS app leads to the same result.

Also exactly the same happens using a generic bluetooth explorer app ([LightBlue Explorer](https://itunes.apple.com/us/app/lightblue-bluetooth-low-energy/id557428110?mt=8)).
Added: The same with the Nordic [nrf Connect for iOS](https://itunes.apple.com/us/app/nrf-connect/id1054362403?mt=8)

There are no clear BT errors occurring on the device (after adding extra code). 

Any plausible app-sided approaches regarding iOS/BLE problems (according SO) did not lead to solutions yet..

Has anyone encountered similiar problems and might have a solution at hand, either app-sided or NRF52-DK-sided?

iPhone 6, iOS 10.2.1 + iPad mini 3, iOS 10.2.0
NRF52-DK (PCA10040, V1.1.1, 2016.48)
NRF5 SDK 12.2.0
Softdevice 332, 2.0.1

**Comment by philips77** [comment]
Hi, it may be related to the fact that new iOS sends mtu request after connection and the firmware seems not to reply. We are investigating it. It's a bug (?) in fw, not in the iOS app. It used to work with older version of iOS.

**Comment by philips77** [comment]
As you may have seen, the question has been answered here:
https://devzone.nordicsemi.com/question/113951/iosiphone-ble-service-discovery-timeout-with-ant-shared-channel-demo/

**Comment by tschiemer** [comment]
That's right - I thought I'd also post it here for any future reference; maybe adding a note to the README might be an idea. Thus I'll also just repeat Petter Myhre's solution here:

I did a sniffer trace, it seems iOS is sending a ATT MTU request that is not responded to, and because of that iOS disconnects after 30s.

If you replace the ble_evt_dispatch() function with the following, the MTU request should be responded to:

In `asc_coordinator.c`:
```
static void ble_evt_dispatch(ble_evt_t * p_ble_evt)
{
    uint32_t err_code;

    cntrldevice_event_handler(p_ble_evt);    

    if(p_ble_evt->header.evt_id == BLE_GATTS_EVT_EXCHANGE_MTU_REQUEST)
    {
        err_code = sd_ble_gatts_exchange_mtu_reply(p_ble_evt->evt.common_evt.conn_handle, GATT_MTU_SIZE_DEFAULT); 
        APP_ERROR_CHECK(err_code);
    }
}
```
I would also like to mention that the iOS app is old (2 years), it is not tested with later SDK, and it will not be updated. It can of course still be used as a starting point for development.
